name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Google Cloud project
      - name: Configure Google Cloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      # Step 4: Deploy to Cloud Run
      - name: Deploy trip-service to Cloud Run
        run: |
          gcloud run deploy trip-service \
            --source . \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=MONGO_URI_TRIP=${{ secrets.MONGO_URI_TRIP }},\
            ROUTE_SERVICE_URL_LOCAL=http://localhost:8080/route-service/routes,\
            ROUTE_SERVICE_URL_PRODUCTION=https://route-service-193893744076.us-central1.run.app/route-service/routes,\
            PERMIT_SERVICE_URL_LOCAL=http://localhost:8081/permit-service/permits,\
            PERMIT_SERVICE_URL_PRODUCTION=https://permit-service-193893744076.us-central1.run.app/permit-service/permits,\
            SCHEDULE_SERVICE_URL_LOCAL=http://localhost:8082/schedule-service/schedules,\
            SCHEDULE_SERVICE_URL_PRODUCTION=https://schedule-service-193893744076.us-central1.run.app/schedule-service/schedules
